Windows:  "%d" is always escaped to "\%d".
Unders Windows, "%d" is always escaped to "\%d". It makes "extract_pages" fail because of below exception.

Docsplit::ExtractionFailed: Unhandled Java Exception in create_output():
java.io.FileNotFoundException: ./abc_\1.pdf: The system cannot find the path specified.